release:
  title-prefix: 'v'
  initial-version: '0.0.1'
  tag-prefix: 'v'
  commit-note-replacers:
    - replace-prefix: 'feat: '
      new-prefix: ''
    - replace-prefix: 'feat!: '
      new-prefix: ''
    - replace-prefix: 'test: '
      new-prefix: ''
    - replace-prefix: 'ci: '
      new-prefix: ''
    - replace-prefix: 'build: '
      new-prefix: ''
    - replace-prefix: 'fix: '
      new-prefix: ''
    - replace-prefix: 'chore: '
      new-prefix: ''
    - replace-prefix: 'docs: '
      new-prefix: ''
branch:
  base-branch: 'main'
  version-branch-prefix: 'v'
  bump-version-commit-prefix: 'v'
categories:
  - title: 'Breaking Changes'
    labels:
      - 'BreakingChange'
    commits:
      - 'feat!:'
    changes-prefix: ':warning: '
  - title: 'Changes'
    labels:
      - 'Feature'
    commits:
      - 'feat:'
    changes-prefix: ':gift: '
  - title: 'Changes'
    labels:
      - CI/CD
    commits:
      - 'ci:'
    changes-prefix: ':hammer: '
  - title: 'Changes'
    labels:
      - Test
    commits:
      - 'test:'
    changes-prefix: ':ledger: '
  - title: 'Bug Fixes'
    labels:
      - 'Bug'
    commits:
      - 'fix:'
    changes-prefix: ':ambulance: '
  - title: 'Changes'
    labels:
      - 'Documentation'
    commits:
      - 'docs:'
    changes-prefix: ':blue_book: '
  - title: 'Chores'
    labels:
      - 'Chore'
    skip-label: 'Development'
    commits:
      - 'chore:'
    changes-prefix: ':green_book: '
bump:
  default: 'patch'
  major:
    labels:
      - 'BreakingChange'
    commits:
      - '*!:'
  minor:
    labels:
      - 'Feature'
    commits:
      - 'feat:'
files:
  - file-path: 'package.json'
    line: 3
