version: '3.1'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - web
      - admin
  web:
    build: .
    environment:
      - API_URL=http://admin:8000
      - PORT=3000
    ports:
      - 3000:3000
    depends_on:
      - admin
  admin:
    image: ghcr.io/eachtech-dev/navhub-admin:latest
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - PORT=8000
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11.2
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db-data:
