name: 'Chromatic'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    env:
      API_URL: https://navhub-admin.herokuapp.com
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          buildScriptName: 'build:storybook'
          exitOnceUploaded: true
          projectToken: '546ee9f895b0'
