name: Docker Build and Push

on:
  repository_dispatch:
    types: [push-docker]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name to push'
        required: true
        default: ''
      push_latest:
        description: 'Push built image as latest, true or false'
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TAG_NAME: ${{ github.event.client_payload.tag_name || github.event.inputs.tag_name }}
    steps:
      - uses: actions/checkout@v2

      - name: Login
        env:
          CR_USERNAME: ${{ secrets.CR_USERNAME }}
          CR_PAT: ${{ secrets.CR_PAT }}
        run: echo $CR_PAT | docker login ghcr.io -u $CR_USERNAME --password-stdin

      - name: Build
        run: docker build . -t ghcr.io/eachtech-dev/navhub:$TAG_NAME

      - if: (github.event_name == 'repository_dispatch' || github.event.inputs.push_latest == 'true' )
        name: Tag latest
        run: docker tag ghcr.io/eachtech-dev/navhub:$TAG_NAME ghcr.io/eachtech-dev/navhub:latest

      - name: Push
        run: docker push ghcr.io/eachtech-dev/navhub
