name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login
        env:
          CR_USERNAME: ${{ secrets.CR_USERNAME }}
          CR_PAT: ${{ secrets.CR_PAT }}
        run: echo $CR_PAT | docker login ghcr.io -u $CR_USERNAME --password-stdin
      - name: Build
        run: docker build . -t ghcr.io/eachtech-dev/navhub:latest
      - name: Push
        run: docker push ghcr.io/eachtech-dev/navhub:latest
